# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pb2/helloworld/helloworld.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'pb2/helloworld/helloworld.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fpb2/helloworld/helloworld.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x99\x02\n\x07Greeter\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12\x33\n\x11SayHelloManyTimes\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x30\x01\x12\x36\n\x14SayHelloClientStream\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00(\x01\x12\x39\n\x15SayHelloBidirectional\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00(\x01\x30\x01\x12<\n\x12SayHelloWithStruct\x12\x17.google.protobuf.Struct\x1a\x0b.HelloReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb2.helloworld.helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=65
  _globals['_HELLOREQUEST']._serialized_end=93
  _globals['_HELLOREPLY']._serialized_start=95
  _globals['_HELLOREPLY']._serialized_end=124
  _globals['_GREETER']._serialized_start=127
  _globals['_GREETER']._serialized_end=408
# @@protoc_insertion_point(module_scope)
