# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/grpc/llm/llm.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protocols/grpc/llm/llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protocols.grpc.common import common_pb2 as protocols_dot_grpc_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotocols/grpc/llm/llm.proto\x12\x12protocols.grpc.llm\x1a\"protocols/grpc/common/common.proto\"\xad\x01\n\nLLMRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12<\n\x07options\x18\x03 \x03(\x0b\x32+.protocols.grpc.llm.LLMRequest.OptionsEntry\x12\x0f\n\x07\x63ontext\x18\x04 \x03(\t\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"p\n\x0bLLMResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06tokens\x18\x02 \x03(\t\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x31\n\x05\x65rror\x18\x04 \x01(\x0b\x32\".protocols.grpc.common.ErrorDetail2\xbe\x01\n\nLLMService\x12S\n\x10GenerateResponse\x12\x1e.protocols.grpc.llm.LLMRequest\x1a\x1f.protocols.grpc.llm.LLMResponse\x12[\n\x16GenerateResponseStream\x12\x1e.protocols.grpc.llm.LLMRequest\x1a\x1f.protocols.grpc.llm.LLMResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.grpc.llm.llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LLMREQUEST_OPTIONSENTRY']._loaded_options = None
  _globals['_LLMREQUEST_OPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_LLMREQUEST']._serialized_start=89
  _globals['_LLMREQUEST']._serialized_end=262
  _globals['_LLMREQUEST_OPTIONSENTRY']._serialized_start=216
  _globals['_LLMREQUEST_OPTIONSENTRY']._serialized_end=262
  _globals['_LLMRESPONSE']._serialized_start=264
  _globals['_LLMRESPONSE']._serialized_end=376
  _globals['_LLMSERVICE']._serialized_start=379
  _globals['_LLMSERVICE']._serialized_end=569
# @@protoc_insertion_point(module_scope)
