# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/grpc/service_info/service_info.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protocols/grpc/service_info/service_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protocols.grpc.common import common_pb2 as protocols_dot_grpc_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.protocols/grpc/service_info/service_info.proto\x12\x1bprotocols.grpc.service_info\x1a\"protocols/grpc/common/common.proto\"\x14\n\x12ServiceInfoRequest\"{\n\tModelInfo\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x1b\n\x13supported_languages\x18\x03 \x03(\t\x12\x19\n\x11support_streaming\x18\x04 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\"\xa7\x01\n\x13ServiceInfoResponse\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x36\n\x06models\x18\x03 \x03(\x0b\x32&.protocols.grpc.service_info.ModelInfo\x12\x31\n\x05\x65rror\x18\x04 \x01(\x0b\x32\".protocols.grpc.common.ErrorDetail2\x89\x01\n\x12ServiceInfoService\x12s\n\x0eGetServiceInfo\x12/.protocols.grpc.service_info.ServiceInfoRequest\x1a\x30.protocols.grpc.service_info.ServiceInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.grpc.service_info.service_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICEINFOREQUEST']._serialized_start=115
  _globals['_SERVICEINFOREQUEST']._serialized_end=135
  _globals['_MODELINFO']._serialized_start=137
  _globals['_MODELINFO']._serialized_end=260
  _globals['_SERVICEINFORESPONSE']._serialized_start=263
  _globals['_SERVICEINFORESPONSE']._serialized_end=430
  _globals['_SERVICEINFOSERVICE']._serialized_start=433
  _globals['_SERVICEINFOSERVICE']._serialized_end=570
# @@protoc_insertion_point(module_scope)
