import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Sidebar for intro.md (empty, only headings/anchors will show)
  introSidebar: [],
  // Sidebar for quickstart folder
    quickstartSidebar: [
      {type: 'doc', id: 'quickstart'},
      {
        type: 'category', 
        label: '範例',
        link: {
          type: "generated-index",
          slug: '/quickstart/examples', // 這裡自訂 URL slug，避免中文出現在 URL
          description: "這是快速入門的索引頁面"
        },
        items: [
          {type: 'autogenerated', dirName: 'quickstart'},
        ]
      }
    ],
  // Sidebar for documents folder
  documentsSidebar: [
    {type: 'doc', id: 'documents'},
    {
      type: 'category', 
      label: '文件', 
      link: {
        type: "generated-index",
        slug: '/documents/all', // 這裡自訂 URL slug，避免中文出現在 URL
        description: "在這裡，你可以找到所有的 Documents。 \nDocuments 是 LLMBrick 的重要組件，負責處理和管理不同的文檔和資源。每個 Document 都有其特定的功能和用途，並且可以根據需要進行配置和擴展。\n你可以在這裡瀏覽各種 Documents 的定義和使用方式，並了解它們如何協同工作來實現更高效的資源管理和服務提供。"
      },
      // This is the index page for the documents category
      items: [
        {type: 'autogenerated', dirName: 'documents'},
      ]
    },
  ]
};

export default sidebars;
