import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Sidebar for intro.md (empty, only headings/anchors will show)
  introSidebar: [],
  // Sidebar for quickstart folder
    quickstartSidebar: [
    {type: 'doc', id: 'quickstart'},
    {
      type: 'category', 
      label: '範例', 
      items: [
        {type: 'autogenerated', dirName: 'quickstart'},
      ]
    }
  ],
  // Sidebar for documents folder
  documentsSidebar: [
    {type: 'doc', id: 'documents'},
    {
      type: 'category', 
      label: '文件', 
      items: [
        {type: 'autogenerated', dirName: 'documents'},
      ]
    }
  ]
};

export default sidebars;
