name: Python CI

on:
  push:
    branches: [ "main", "master" ]
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches: [ "main", "master" ]
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt || true
        pip install -e .

    # - name: Lint with flake8
    #   run: |
    #     flake8 llmbrick

    # - name: Type check with mypy
    #   run: |
    #     mypy llmbrick

    - name: Run tests
      run: |
        pytest